### PR TITLE
Amended Travis build matrix

### PR DESCRIPTION
**Pull request by sergeyklay**
- Add Emacs 25 and Emacs 26 to the Travis build matrix

### CODE REVIEW

**Comment by sergeyklay** [comment]
@Fanael Is Travis CI integration enabled?

**Comment by Fanael** [comment]
It was, not sure what happened to it.

**Comment by Fanael** [comment]
Looks like mechanism the was used to integrate with Travis was deprecated, let me migrate everything to the new one.

**Comment by Fanael** [comment]
Travis is being silly, I'm gonna merge it and try fixing the integration later.

**Comment by sergeyklay** [comment]
Thank you

**Comment by Fanael** [comment]
I fixed CI by ditching Travis altogether and moving to GitHub Actions.

**Pull request merged**
